accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),
]

api/urls.py
from rest_framework import routers
from .views import ToDoViewSet

router = routers.DefaultRouter()
router.register('entries', ToDoViewSet, basename='todo')
urlpatterns = router.urls

config/urls.py
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token

# from api.urls import router as api_urls

urlpatterns = [
    path('', include('todo.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include("api.urls")),
    path('api/token/', obtain_jwt_token)
]

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('new/', views.New.as_view(), name='new'),
    path('update/<int:pk>', views.Update.as_view(), name='update'),
    path('done/<int:pk>', views.Done.as_view(), name='done'),
    path('delete/<int:pk>', views.Delete.as_view(), name='delete'),
]

todo/models.py
from django.db import models
from accounts.models import CustomUser


class ToDo(models.Model):

    class Meta:
        db_table = 'todo'

    user = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, verbose_name='投稿ユーザ')
    name = models.CharField(max_length=200, verbose_name='ToDo名')
    content = models.CharField(max_length=10000, verbose_name='ToDo内容')
    create_date = models.DateTimeField(auto_now_add=True)
    done_date = models.DateTimeField(null=True)
    is_done = models.BooleanField(default=False)
    is_hidden = models.BooleanField(default=False)

todo/forms.py
from django import forms

from .models import ToDo


class ToDoForm(forms.ModelForm):

    class Meta:
        model = ToDo
        fields = ("name", "content")

    content = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'ToDoの内容を入力してください。'}), label='内容',)

    def __init__(self, *args, **kwargs):
        super(ToDoForm, self).__init__(*args, **kwargs)
        self.fields["name"].label = 'ToDo名'
        self.fields["name"].widget.attrs = {'placeholder': 'ToDo名を入力してください。'}

todo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import CreateView, TemplateView, UpdateView

from .forms import ToDoForm
from .models import ToDo


class UserCheck(UserPassesTestMixin):
    """
    ログインユーザーとToDo所有ユーザーの適合チェック

    """

    def test_func(self):
        todo_id = self.kwargs["pk"]
        todo = get_object_or_404(ToDo, pk=todo_id)
        user_id = self.request.user.id

        return todo.user_id == user_id

    def handle_no_permission(self):
        return render(self.request, 'todo/no_permission.html')


class Index(LoginRequiredMixin, TemplateView):
    """
    Indexページ:
    未完了/完了済ToDoの表示
    """
    template_name = 'todo/index.html'

    def get_context_data(self, **kwargs):
        """
        未完了/完了済ToDを取得しTemplateの変数に追加

        Returns
        -------
        context : dic
        未完了/完了済ToD
        """
        user_id = self.request.user.id
        context = super().get_context_data(**kwargs)
        context["user_name"] = self.request.user.username
        # 未完了ToDoの取得
        context["in_progress_todo"] = ToDo.objects.filter(user_id=user_id,
                                                          is_done=False,
                                                          is_hidden=False).order_by('-id')
        # 完了済ToDoの取得
        context["done_todo"] = ToDo.objects.filter(user_id=user_id,
                                                   is_done=True,
                                                   is_hidden=False).order_by('create_date')

        return context


class New(LoginRequiredMixin, CreateView):
    """
    新規ToDo作成View:
    GETアクセス時はからのフォームを表示
    POSTアクセス時はform_validメソッドでToDo作成
    """
    form_class = ToDoForm
    template_name = 'todo/new.html'
    success_url = reverse_lazy('todo:index')

    def form_valid(self, form):
        """
        バリデーションに問題がなけれなToDoを保存
        """
        new_todo = form.save(commit=False)
        # ログイン中ユーザーをToDo所有ユーザーに設定
        new_todo.user_id = self.request.user.id
        new_todo.save()

        return super().form_valid(form)


class Update(LoginRequiredMixin, UserCheck, UpdateView):
    """
    ToDo更新View:
    GETアクセス時は登録済ToDoをフォームの初期値に設定
    バリデーションに問題がなければToDoを更新
    """
    model = ToDo
    field = ['name', 'content']
    form_class = ToDoForm
    template_name = 'todo/update.html'
    success_url = reverse_lazy('todo:index')

    def get_initial(self):
        """
        保存済ToDoをFormの初期値に設定

        Returns
        -------
        initial : dic
        保存済ToDo name: ToDo名
                  context: ToDoの内容
        """
        initial = super().get_initial()
        todo_id = self.kwargs["pk"]

        todo = get_object_or_404(ToDo, pk=todo_id)
        initial = {
            'name': todo.name,
            'content': todo.content,
        }
        return initial


class Done(LoginRequiredMixin, UserCheck, View):
    """
    ToDo完了処理View:
    """

    def get(self, request, pk):
        """
        ToDoを完了済ステータスに変更する

        Parameters
         ----------
        pk : int
        todoのid
        """
        # モデルからレコードを取得
        todo = get_object_or_404(ToDo, pk=pk)

        # 現在時刻(ToDo完了時刻)と完了フラグを設定し保存
        todo.done_date = timezone.now()
        todo.is_done = True
        todo.save()

        return redirect(reverse('todo:index'))


class Delete(LoginRequiredMixin, UserCheck, View):
    """
    ToDo削除処理View
    """

    def get(self, request, pk):
        """
        ToDoを削除(非表示に)する

        Parameters
         ----------
        pk : int
        todoのid
        """
        # モデルからレコードを取得し非表示に設定
        todo = get_object_or_404(ToDo, pk=pk)
        # 非表示フラグをTrueに設定
        todo.is_hidden = True
        todo.save()

        return redirect(reverse('todo:index'))

templates/todo/detail.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}
    ToDo - Detail
{% endblock %}

{% block content %}

<div class='container'>
    <h1>ToDoの詳細</h1>

    <a href="{% url 'todo:index' %}" class="btn btn-primary btn-sm my-3 text-left">戻る</a>

    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="text-center">
            <input class="btn btn-success" type="submit" value="保存">
        </div>
    </form>
</div>

{% endblock %}

templates/todo/index.html
{% extends 'base.html' %}

{% block bootstrap4_title %}
    ToDo - Home
{% endblock %}

{% block content %}

<div class='container'>
    <h1>ToDo</h1>

    <a href="{% url 'todo:new' %}" class="btn btn-primary btn-sm my-3">新しいToDoの追加</a>
    <a href="{% url 'accounts:logout' %}" class="float-right btn btn-primary btn-sm my-3">ログアウト</a>

    {% comment %} 進行中のToDoを表示するテーブル {% endcomment %}
    <div class="in_progress_todo">
        <table class="table table-striped table-bordered">
            <h3>進行中</h3>
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">ToDo名</th>
                    <th scope="col">作成日</th>
                    <th scope="col">操作</th>
                </tr>
            </thead>
            <tbody>
            {% for todo in in_progress_todo %}
                <tr>
                    <td id="todo_id">{{ todo.id }}</td>
                    <td>{{ todo.name }}</td>
                    <td>{{ todo.create_date }}</td>
                    <td>
                        <a href="{% url 'todo:update' pk=todo.id %}" class='btn btn-outline-primary btn-sm'>編集</a>
                        <a href="{% url 'todo:done' pk=todo.id %}" class='btn btn-outline-success btn-sm'>完了</a>
                    </td>
                </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>

    {% comment %} 完了済のToDoを表示するテーブル {% endcomment %}
    <div class="done_todo">
        <table class="table table-striped table-bordered">
            <h3>完了済</h3>
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">ToDo名</th>
                    <th scope="col">作成日</th>
                    <th scope="col">完了日</th>
                    <th scope="col">操作</th>
                </tr>
            </thead>
            <tbody>
            {% for todo in done_todo %}
                <tr>
                    <td>{{ todo.id }}</td>
                    <td>{{ todo.name }}</td>
                    <td>{{ todo.create_date }}</td>
                    <td>{{todo.done_date}}</td>
                    <td>
                        <a href="{% url 'todo:update' pk=todo.id %}" class='btn btn-outline-primary btn-sm'>編集</a>
                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal">
                            削除
                        </button>

                        {% comment %} 削除を確認するモーダル ダイアログ {% endcomment %}
                        <div class="modal" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteModalLabel">確認</h5>
                                    </div>
                                    <div class="modal-body">
                                        このToDoを削除しますか？
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">キャンセル</button>
                                        <a href="{% url 'todo:delete' pk=todo.id %}" class='btn btn-danger btn-sm'>削除</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/todo/new.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}
ToDo - New
{% endblock %}

{% block content %}

    <div class='container'>
        <h1>新しいToDoの作成</h1>

        <a href="{% url 'todo:index'%}" class="btn btn-primary btn-sm my-3 text-left">戻る</a>

        <form method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="text-center">
                <input class="btn btn-success" type="submit" value="作成">
            </div>
        </form>
    </div>

{% endblock %}

templates/todo/no_permission.html
編集権限がありません。
<a href="{% url 'todo:index' %}" class="text-right btn btn-primary btn-sm my-3">ホームへ</a>

templates/todo/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}
    ToDo - Update
{% endblock %}

{% block content %}

<div class='container'>
    <h1>ToDoの更新</h1>

    <a href="{% url 'todo:index' %}" class="btn btn-primary btn-sm my-3 text-left">戻る</a>

    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="text-center">
            <input class="btn btn-success" type="submit" value="保存">
        </div>
    </form>
</div>

{% endblock %}